### ISSUE TITLE
기능구현 - 쇼핑몰 메인(index)

### ISSUE THREAD

**Issue by Mohenic** [Mohenic/Kmarket#40]
- http://localhost:8080/Kmarket/index.do
- 스토리보드 개발 가이드 참고
- [ ] 상품 카테고리 기능구현
- [x] 베스트상품 목록 구현
- [x] 히트상품 목록 구현
- [x] 추천상품 목록 구현
- [x] 최신상품 목록 구현
- [x] 할인상품 목록 구현

**Comment by haminsu1234** [comment]
2023.09.15 히트,추천,최신,할인상품 목록기능 구현 시작

**Comment by haminsu1234** [comment]
2023.09.16  히트,추천,최신,할인상품 목록기능 구현완료 

2023.09.16  나머지기능 구현 시작

**Comment by haminsu1234** [comment]
2023.09.17 베스트상품 목록 구현완료 
css 작업중

**Comment by haminsu1234** [comment]
2023.09.18 기타 세부내용 수정 (자리수 ,찍기 조건에따른 할인가격 반영등)

2023.09.18 남은작업 : aside link 수정(product 파트와 맞춰야 해서 대기중)

**Comment by haminsu1234** [comment]
2023.09.22 : aside 링크 수정 완료 나머지 링크 대기중
